### ISSUE TITLE
Cycle Diversity: generalize for any stream library

### ISSUE THREAD

**Issue by staltz** [cyclejs/core#196]
@TylorS and I started discussing how to migrate to RxJS 5, and/or support *most.js* streams without the need for a fork (Motorcycle.js) which mostly has copy-pasted code from some Cycle.js libraries.

We arrived at a proposal: **Build a "base" run() function which is generic and assumes no stream library. It uses "stream adapters" to agree on an interface for each stream library. We need to build an adapter for each stream library. We also need to build "rx run()", "most run()" which basically utilizes the common "base run()" but specify which stream library adapter is used. Drivers are given the stream adapter object from run(), and can written using whatever stream library**.

`@cycle/rx-run`
```js
import baseRun from '@cycle/base'
import streamAdapter from '@cycle/rx-adapter'

const Cycle = {
  run: (main, drivers) => baseRun(main, drivers, {streamAdapter})
}

export default Cycle
```

`@cycle/dom`
```js
function domDriver(sink$) {...}

domDriver.streamAdapter = rxAdapter // mostAdapter 
```

- - - 

## Tasks to do

- [x] Create `@cycle/base` repo (essentially this PR #198 there) https://github.com/cyclejs/base
- [x] Write test for `@cycle/base` ensuring one-liner drivers work properly with default adapter.
- [x] Build https://github.com/cyclejs/rx5-adapter with tests, using StreamAdapter interface from base
- [x] Build https://github.com/cyclejs/rx4-adapter with tests, using StreamAdapter interface from base
- [x] PR on Cycle Core to implement it as `@cycle/base + @cycle/rx-adapter`, with #200 in mind
- [x] Make canary version for `core`
- [x] Make `@cycle/rx-run` npm package alias for `@cycle/core`
- [x] Rewrite Cycle DOM Driver in TypeScript with transposition off by default
- [x] Update base to export CycleSetup interface
- [x] Fix Cycle DOM diversity to adapt the out-facing streams for the app's stream library
- [x] Convert some cycle-examples to use the canary version of `dom` with RxJS 5
- [x] Cycle HTTP driver in TypeScript and using `driverFn.streamAdapter = rxAdapter`
- [x] Make canary versions for `http`, test it around
- [x] Update power-ui to Diversity
- [x] xstream-adapter
- [x] xstream-run
- [x] Fix Cycle DOM last bugs with DOMSource.events() and isolate
- [x] Soft release `core`, `dom`, `*-run`, `http`, `jsonp` RC versions
- [x] Build https://github.com/cyclejs/most-adapter in JS with tests, using StreamAdapter interface from base
- [x] create `@cycle/most-run` https://github.com/cyclejs/most-run with #200 in mind
- [x] *Unnecessary*: Update motorcycle drivers to use `driverFn.streamAdapter = mostAdapter`
- [x] Update examples and TodoMVC to Diversity & xstream
- [x] Make bmi-typescript example, and fix Cycle DOM TypeScript problems, issue #307
- [x] Write http-random-user in TypeScript to make sure HTTP Driver is also working well
- [x] Change HoldSubject to Subject in stream adapters. It's not needed.
- [x] Rework makeHTMLDriver(callback)
- [x] mockDOMSource should return a stream of the app's own stream library.
- [x] DOMSource.select().elements should return WhateverStream interface, not type `any`
- [x] foo-adapter and foo-run: remove dispose(), add remember()
- [x] Update cycle history to use stream adapter remember()
- [x] Update TodoMVC using cycle history
- [x] Fix Cycle DOM documentation generation
- [x] Update cycle.js.org
- [x] cycle.js.org documentation page
- [x] Write Release notes and migration guide
- [x] Merge branches `diversity` to `master`, and publish non-rc versions
  - [x] Cycle Core / Rx Run
  - [x] DOM
  - [x] HTTP
  - [x] JSONP
  - [x] examples
  - [x] cyclejs.github.io
  - [x] others
- [x] npm deprecate `@cycle/core`, use rx-run
- [x] Cycle DOM rxjs-typings, rx-typings, most-typings
- [x] Cycle HTTP rxjs-typings, rx-typings, most-typings

## Breaking changes so far

- `DOMSource.select().observable` => `DOMSource.select().elements()`
- new Cycle.run API for those cases where sources and sinks are wanted: #200 
- Snabbdom instead of virtual-dom
  - breaking changes with hyperscript way of using attrs
- top-level `<svg>` element is created with hyperscript-helpers but children elements created with hyperscript
- mockDOMSource(sa, config) now takes a Stream Adapter as the first argument
- `makeHTMLDriver()` => `makeHTMLDriver(effectFn, options)`
- No more onError callback as an option to makeDOMDriver()
- No more sinks.dispose and sources.dispose
- HTML Driver returns and HTMLSource mimicking DOMSource. `HTMLSource.element$` is the stream of HTML strings
- HTTP Source is not `response$$` but contains it. It's an object with `select(category: string): Observable<Observable<Response>>`, `filter(predicate: (res$: ResponseStream) => boolean): HTTPSource` and `response$$` property.

**Comment by erykpiast** [comment]
I'm not sure if I understand correctly, so please tell me, which statement is the closest to your idea.

 1. you wish to allow people to create Cycle drivers with whatever library they want, not only Rx, and make Cycle-core transparent (library agnostic), so if all the drivers are written with, ex., `most.js`, application may be written using `most` too and there is no dependency on Rx?
 2. or you propose to make inside Cycle kind of translation from `any-streams-library.js` to `other-stream-library.js`, to allow different drivers be written with different libraries and application in any other supported library?

**Comment by TylorS** [comment]
I have already begun experimenting with this here at https://github.com/TylorS/cycle-core/tree/rxjs-most-interoperability. It requires no breaking changes to the current cycle-* drivers. Most.js drivers are supported using (this is not a agreed upon or final API)

```js
function driverFn() {}
driverFn.type = 'most'
```

There are some issues still that need to be resolved. Cycle-DOM for example has 2 failing tests, but I haven't had the time just yet to investigate the issues. 

I'm also interested in simply creating a set of streamLibrary -> streamLibrary conversion functions to experiment with drivers being in control of where to convert from one library to another.

**Comment by erykpiast** [comment]
"streamLibrary -> streamLibrary" approach would make Cycle's interoperability and interchangeability outstanding! Especially if it's done inside core (or somewhere else, but to make it transparent to the framework user and driver creator).

**Comment by staltz** [comment]
@erykpiast The purpose of this issue/initiative is to:

- Allow `main()` to be written in any of these stream libraries: RxJS 4, RxJS 5, most, Bacon.js, Kefir.
- Allow using *most*-based drivers, such as Motorcycle's outstanding *most* + snabbdom driver.
- Keep the simple API for drivers: just functions that input and/or output streams. In particular, it's important to allow people to create one-liner drivers without a lot of boilerplate. We need a solution that assumes drivers, unless specified, are using the same stream library used by `run()` when specified in `options.streamLibrary` in `Cycle.run(main, drivers, options)`.

**Comment by TylorS** [comment]
I'm working on an external library to convert between different stream implementations. I believe it will likely be required for a driver to supply a place to be able to convert it's streams when there are more complex streams such as the DOM Driver.

**Comment by staltz** [comment]
Great :+1: 
Modularity for the win

**Comment by erykpiast** [comment]
What about interoperability of nested cycles? There is plan to make possible connections between cycle applications built with different libraries? To be honest I don't really believe people would like to use many stream libraries in production-ready applications (at the end of the day size matters), but if we make it possible for drivers, it will be consistent to provide the same abilities to nested cycles.

@TylorS do you think this conversion utility should be used in drivers internally? I see another possible approach: for drivers like Cycle-DOM, thin compatibility layers may be built, one for each library. If driver creator defines some interface to build ex. multi-level streams, implementation (from separated package like `cycle-dom-kefir`) may be passed to the driver.

```
import { run } from '@cycle/core';
import makeDomDriver from '@cycle/dom';
import kefirAdapter from '@cycle/dom-kefir-adapter';

Cycle.run(main, {
  DOM: makeDomDriver('#app-container', kefirAdapter)
});
```

The adapter will implement functions like `createEventsStream` etc. in Kefir, using stream conversion library internally. Driver itself will stay small and library agnostic, hovewer its configuration will become more complicated.

Just an idea.

**Comment by staltz** [comment]
We can always endlessly abstract everything away, but I don't think that's the purpose. It's enough if we allow people to build `main()` in their preferred stream library. For nested components (if I understood that's what you meant by "nested cycles") I think a better idea will be a utility library to convert a Cycle `main()` to a Web Component (or a Web standard custom element).

**Comment by TylorS** [comment]
@erykpiast Your approach is bascially what I have in mind, but converting from one to another is actually pretty easy and general so it would probably be handled as an option to `run()`. This is just an idea too.

```js
function driverFn(sink$, conversionFn) {
  return conversionFn(sink$.map(x => x * x))
}

driverFn.streamLibrary = 'rx' // Tells run that it's written in rx

run(main, {other: driverFn}, {streamLibrary: 'rx'}) // means write your main() with Rx
run(main, {other: driverFn}, {streamLibrary: 'most'}) // write your main() with most
```

So anywhere that a stream is produced and returned back to main, `conversionFn()` would just have to be called to convert the stream from x -> y.

**Comment by HighOnDrive** [comment]
Very exciting, Cycle as a "Web Component (or a Web standard custom element)" sounds great too. Embedding anywhere everywhere sounds like a famous-ly awesome idea!

**Comment by TylorS** [comment]
Here is the start of this stream conversion library
https://github.com/TylorS/stream-conversions

**Comment by staltz** [comment]
:+1: I like the API!

**Comment by Cmdv** [comment]
I like the idea giving devs the option to chose stream library of preference. 
But I worry a little with giving people support. Most & Rx are quite similar and all the examples on Docs assume Rx but how do we support people using Bacon.js?
Just wonder if it will add a level of confusion as to what the right way to do things would be. 
Superb for people with previous Cycle experience but a little daunting for new comers?
Just a devils advocate thought process but I always like to think of new comers :)

**Comment by staltz** [comment]
Good concerns @Cmdv. The point here is to give choice. That's different from forcing people to choose. I'll still advocate in cycle.js.org docs one stream library (most likely RxJS 5), but I'm happy to support people who want (or need) to use `most` or Bacon.js or anything else. For people who know what they need, I want to make it easy. For people who don't know what they need, I also want to make it easy.

I'm still planning to write that "Real world apps" chapter for cycle.js.org, where there will be a suggested stack of tools.

**Comment by TylorS** [comment]
@staltz This API for which?  `stream-conversions` or above that for drivers?

@Cmdv I don't know anything about Bacon.js or any of the other libraries, but I think we're just getting started with just Rx and Most. Basically the idea is to have an approach to allow Cycle.js to be a general implementation of a pattern, ultimately paving the way for when we can just use ES standard Observables and the interoperability that will bring.

**Comment by staltz** [comment]
stream-conversions

**Comment by Cmdv** [comment]
@staltz @TylorS lovely I just wanted to make sure there was an advocated way and more experienced Devs could chose the stream library of choice.

Didn't want to add lots of confusion to the table, because Cycle and FRP isn't the easiest thing to get your head around if you've never used streaming libraries. So clarity and less abstraction is needed for those new devs. This can be just at a Documentation level or advocated level but wanted to make sure new dev's weren't coming to cycle thinking:

What are these stream libraries which one do I use? I just want to have a little play and already I have to make important choices about the core of what I'm building.

Then ultimately scaring them off :)

**Comment by TylorS** [comment]
@Cmdv The default for the foreseeable future at least will be rx 4 and rx 5 when that's ready. I don't think there is any current plan or need for breaking changes application side. This should all be handled in `run()` and inside of the drivers transparently.

**Comment by staltz** [comment]
Actually one of the biggest things is being able to use *most.js* in a DOM Driver. In principle it should have better performance.

**Comment by TylorS** [comment]
@staltz Yes, that's another good reason.

*Most.js* in theory can be anywhere from ~200x-400x* faster than Rx 4 and still roughly 30x-50x* faster than Rx 5 so even with these conversions there should still be a performance boost where there are expensive operations like diffing and patching the DOM.

(\* - https://gist.github.com/TylorS/55573b29df19c064c6b1)

**Comment by Cmdv** [comment]
Agreed, I'm really liking the idea to let `run()` handling that behind the scene and perf improvement is always a good route to take.

Also if there is a core Rx library that could fit in really nicely rather than the whole of Rx.

Would you be able to mix say Cycle-dom use `most.js` and run use Rx etc? I assume thats what @TylorS stream-conversions is about?

**Comment by TylorS** [comment]
@Cmdv Yes, thats the idea. The drivers can be written in `x` and your application will be written in whatever library you prefer.

```js
run(main, driver, {streamLibary: 'rx'}) // write your application using RxJS
run(main, driver, {streamLibary: 'most'}) //write your application using Most.js
```

**Comment by Cmdv** [comment]
Great this is a nice way to have everyone working together too :+1:

**Comment by HighOnDrive** [comment]
Very nice indeed :+1:

**Comment by TylorS** [comment]
Yes! Motorcycle will essentially will be rolled back into Cycle.js :+1:

**Comment by TylorS** [comment]
My [stream conversion library](https://github.com/TylorS/stream-conversions) has been updated to make use of an interface to allow for easier support of additional libraries and quite a bit less code overall. Tests are now partially generated, in a way, too! I'll try to get started on a version of cycle-core that takes advantage of this, and add support for some of the common drivers. e.g. cycle-dom and cycle-http

**Comment by TylorS** [comment]
I opened PR #197  for my work on stream conversions being done in run(). Drivers would now passed a function as the second parameter for use of converting between streams between different libraries.

**Comment by Frikki** [comment]
Very interesting. An idea we discussed months ago. Hopefully, I’ll soon be back working with you lot.

**Comment by staltz** [comment]
@Frikki :blue_heart:

**Comment by Frikki** [comment]
`@cycle/dom`

```js
function domDriver(sink$) {...}

domDriver.streamAdapter = rxAdapter // mostAdapter 
```

I don’t understand this. Will *@cycle/dom* have a default *rxAdapter*? Or where in which file does this line appear `domDriver.streamAdapter = rxAdapter`? Doesn’t that create an *Rx* dependency? If I want to use *mostAdapter*, how do I do that?

**Comment by staltz** [comment]
@TylorS we need to rename some things in the Adapter interface:

```diff
 interface Adapter {
-  replaySubject(): any;
+  makeHoldSubject(): any;
   dispose(sinks: any, sinkProxies: any, sources: any): void;
-  replicate(stream: any, sink: Sink): void;
+  replicate(stream: any, observer: Observer): void;
-  isAdaptedStream(stream: any): boolean;
+  isValidStream(stream: any): boolean;
-  streamSubscription(stream: any, sink: Sink): void;
+  subscribeToStream(stream: any, observer: Observer): Disposable;
-  adaptation(fromStream: any, fromStreamSubscriptionFunc: Function): any;
+  adapt(originStream: any, subscribeToOriginStream: Function): any;
}
```

And the Sink type to be renamed to Observer (it's important that its name doesn't clash with driver sink/source):
```diff
-interface Sink {
+interface Observer<T> {
-  add(x: any): void;
+  next(x: any): void;
   error(e: any): void;
-  end(): void;
+  complete(): void;
}
```

^ Names `next/error/complete` above are from ES7 Observable.

**Comment by staltz** [comment]
@Frikki drivers will be written always in a specific stream library, so they will have a peerDependency on that stream library. That snippet of code was meant to be library code, not user land code.

**Comment by TylorS** [comment]
@staltz Yes, we should definitely work to standardize the interface further. I'm okay with the changes you propose. 

@Frikki any thoughts on them?

**Comment by Frikki** [comment]
After reviewing functional programming standards, verbs denote referentially transparent functions, and nouns denote immutable data. So I guess I am fine with the changes. But can I see the current adapter interface file? Where does it live?

**Comment by staltz** [comment]
@Frikki there isn't the "object" type in TypeScript.

**Comment by TylorS** [comment]
@staltz There is a type 
```typescript
const x: Object = {some: thing}
```

**Comment by Frikki** [comment]
@staltz Ha ha. Didn’t know that. Would it then be more correct

```js
Type HoldSubject = {
  observer: Observer,
  stream: any
}
```
and in `interface Adapter`
```js
makeHoldSubject(): HoldSubject
```
?

**Comment by Frikki** [comment]
@staltz Could you put a README file in the *base* repo, so we can fork it and make PRs? Many thanks.

**Comment by staltz** [comment]
Sure thing. About the `HoldSubject` interface, that's correct. And as you can see you can indefinitely start giving more and more types.

**Comment by staltz** [comment]
Done

**Comment by Frikki** [comment]
@staltz Is *base* supposed to be written in TypeScript?

**Comment by staltz** [comment]
Everything is eventually. The sooner, the better.

**Comment by gregpardo** [comment]
Wonder if it's possible to provide a generic interface for drivers that would use whichever stream library the user specified. Pass the driver an adapter and it will use that. That's probably a whole new level of complex though because you would have to restrict drives to a simple stream API if they wanted to support the feature.

**Comment by BenBals** [comment]
There is a proposal for an Observable as a language feature. It's currently in stage 1, but it may still be worth consideration. The campions of this proposal published it at https://github.com/zenparsing/es-observable and https://zenparsing.github.io/es-observable/

**Comment by rickmed** [comment]
not sure if this belongs in another issue...Regarding the DOM driver and plans for using snabbdom. 

Have you looked at this https://github.com/trueadm/inferno? (just the virtual dom library). There's a benchmark being it +2x faster than snabbdom and ~4x faster than virtual-dom. 

Also, there is https://github.com/rickmed/inferno-helpers which uses the exact same syntax as hyperscript helpers

**Comment by rickmed** [comment]
not sure if this belongs in another issue...Regarding the DOM driver and plans for using snabbdom.

Have you looked at this https://github.com/trueadm/inferno? (just the virtual dom library). There's a benchmark being it +2x faster than snabbdom and ~4x faster than virtual-dom. Also, it seems simpler.

Also, there is https://github.com/rickmed/inferno-helpers which uses the exact same syntax as hyperscript helpers

**Comment by TylorS** [comment]
@rickmed If you're familiar with inferno (I'm not) I'd love you help investigating its viability as an alternative DOM driver for Cycle. You can checkout my progress [here](https://github.com/tylors/cycle-inferno), but I'm very hesitant that it's speed will translate to Cycle.

**Comment by marszall87** [comment]
So is it possible to use Cycle with RxJS 5 right now?

**Comment by staltz** [comment]
Nope, because this feature isn't done.

**Comment by niieani** [comment]
@marszall87 I've been using the [issue196](https://github.com/cyclejs/core/tree/issue196) branch of CycleJS with RxJS 5 without any problems. Mind you, I'm not using the official DOM driver which isn't ready yet (I'm writing my own drivers). It works as expected and described here. If that's what you mean, all you need to do is install the beta:

```shell
npm install @cycle/core@7.0.0-rc1 --save
```

**Comment by SteveALee** [comment]
I'm realise I'm late to the discussion but wanted to say I'm really pleased you're keeping cyclejs 'opinionated yet flexible'. It's important for addoption. I completely echo @Cmdv's concerns about ensuring it remains easy to pick up cycle. It provides really clean model for using RP and if like me you've already come the very long way round via many web app technologies then having more choices to make would probably have caused me to move on :) It's enough rewiring your brain for RP, let alone exploring different implementations.

IMHO the 'default' option should be lean and mean in terms of brain power need, API surface area and performance. So perhaps that means snabdom eventually But RX is a great choice. Especially if it will have a smaller footprint in Rx 5 (I understand there will be no full / lite split).

The proposal sounds great.

**Comment by SteveALee** [comment]
PS [Netflix mention](http://techblog.netflix.com/2016/03/how-we-build-code-at-netflix.html) the concept of the 'Paved Road' for the most common and best supported developer tooling. I like that and think it fits here too. We have the paved road but devs are free to go off road if they like as long as they accept the extra work that it might involve.

**Comment by staltz** [comment]
Yes @SteveALee our plan is to precisely give a reasonable default option to the developer, so she doesn't need to pick/choose when starting a project. This is after all a framework, not a library. But we also want to give developers freedom of some choice, without being an obstacle in their way.

**Comment by SteveALee** [comment]
:+1:

**Comment by staltz** [comment]
PS: please don't :+1: comments, ever. There is now the reactions feature in GitHub, so just use that. Thanks and sorry for being curt about it.

**Comment by SteveALee** [comment]
Sure, I would have but stupidly they are not available on the github mobile Web app. :(

**Comment by laszlokorte** [comment]
Shouldn't `DOMSource.select().element$` be called `DOMSource.select().elements$` because the stream does not contain only one element but an array of matching elements?

**Comment by staltz** [comment]
Perhaps it should. We're also considering renaming `events` => `event$`. These two things would make the dollar convention official, as opposed to optional as it was before.

**Comment by creatorrr** [comment]
Would be great to get started writing docs and examples for writing stream adapters. Is the API stable enough for that?

**Comment by staltz** [comment]
No, not yet. We might change some things with stream adapters. And I'm not sure we need even docs for that. There's only a handful of stream libraries, and we don't want Cycle.js users to feel like they need to know about stream adapters. In fact, it's a framework-internal thing and they shouldn't need to know about it.

**Comment by creatorrr** [comment]
I see. Although, given that Web-streams will be shipping natively in browsers soon, we could safely assume a deluge of higher level streams libraries.

**Comment by whitecolor** [comment]
> Web-streams will be shipping natively in browsers soon

yes, like observers and http2, soon

**Comment by SteveALee** [comment]
heh, and don't forget web components.

**Comment by tusharmath** [comment]
Here is another thought, how about the API being exposed via simple callbacks or event emitters. This would make the API much simpler to consume and convert to whichever stream people want to use. This would also encourage people to write truly stream agnostic drivers which is a must have.

**Comment by whitecolor** [comment]
@tusharmath what API? you actually may use adapter's API to create lib agnostic drivers.

**Comment by tusharmath** [comment]
@whitecolor 
>which api
The `Cycle.run` method could actually get rid of any dependency on a stream lib completely. 

Here are my concerns in detail —
- I am using most.js for my application and I will still have a copy of the humungous `RxJS` lib simply because `Cycle` depends on it. IMHO letting go of Rx or any other streaming lib will make cycle easier to adopt and also not be limited by the performance of that streaming lib. Every now and then there is going to be something _faster_ and its not realistic to expect Cycle and its drivers to immediately upgrade.
- Cycle is about following a `MVI` pattern but should not be enforcing FRP as a way to achieve it. FRP makes literally everything easier, but that should not become a criteria for how Cycle's interface is designed.

**Comment by staltz** [comment]
@tusharmath There will be a Cycle.run for each stream library, e.g. `@cycle/rx-run`, `@cycle/most-run` etc. Cycle Diversity is about making these libraries with each other so that if you have a driver written in most, you can use it even though your app is in Rx. But the endgoal with all this is to gradually and softly migrate to xstream. If we had started from the beginning with xstream, Cycle Diversity and the interop between these stream libraries would not be necessary.

**Comment by Cmdv** [comment]
@staltz is the long term goal, to have xstream be the only streaming library involved?

**Comment by staltz** [comment]
I don't mean we will cut support for other libraries. That's not the point. The point is that xstream is meant for Cycle and Cycle for xstream.

**Comment by whitecolor** [comment]
> But the endgoal with all this is to gradually and softly migrate to xstream. If we had started from the beginning with xstream, Cycle Diversity and the interop between these stream libraries would not be necessary.

I can not completely agree with this. I believe cycle has potential of staying/becoming really stream library agnostic framework, and no need to set this restricting "endgoal". I believe `@cycle/core` will become eventually `xstream-run` instead of `rx-run`. Time will show if *Cycle meant for xstream* is better vision. 

@tusharmath for using components that were developed with different stream libs I've created #305

**Comment by edge** [comment]
@whitecolor Diversity is cool and all, but if we want to have minimal bundle sizes and maximum performance, then sticking to one stream implementation is the way to go.

The last thing we want to do is to send the client a >1 MB distribution including `xstream`, `rx`, `most`, `bacon`, and `kefir` just because we flaunted the ability to choose whatever stream library suited your fancy.

**Comment by staltz** [comment]
@edge Not just that, but having more choices leads to more choice paralysis for beginner programmers, but it also means more maintenance for the core developers. I am building Cycle as a framework with smart defaults, but with some degree of choice/freedom, not as a generic layer for everything anyone wants.

**Comment by whitecolor** [comment]
@edge nothing restricts you from this with diversity approach. Use drivers and components written with your library of choice. 

And I agree that `xstream` can become a good standard for shared components. But i'm also convinced that harmonic approach to diversity will only make framework stronger.

**Comment by download13** [comment]
I'm curious why xstream was chosen over something that could be more interoperable like [es-observable`](https://github.com/zenparsing/es-observable).

If the spec is added to a future version of JavaScript we'll likely have a built-in implementation of `Observable` that all libraries can use (much like Promise). At that point libraries will only need to depend on utility functions, which can be imported as bundles (a la rx) if they don't mind being bulky or individually (something like `@cycle/flatMapLatest`).

**Comment by staltz** [comment]
I am closely following `es-observable` closely and I am involved in discussions. For now, it is a moving target. We are building Cycle Diversity with tools from today, not from tomorrow.

**Comment by staltz** [comment]
Done: https://github.com/cyclejs/core/releases/tag/v7.0.0

**Comment by mightyiam** [comment]
Yay! Good job!
